#!/bin/bash
#
# Title:      PlexGuide (Reference Title File)
# Author(s):  Admin9705
# URL:        https://plexguide.com - http://github.plexguide.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # FACTS #######################################################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'jellyfin'
        intport: '8096'
        extport: '8096'
        image: 'jellyfin/jellyfin'

    # CORE (MANDATORY) ############################################################
    - name: 'Including cron job'
      include_tasks: '/opt/plexguide/containers/_core.yml'

    # MIGRATIONS (REMOVE SECTION ON MARCH 1st) #############################################################
    - name: 'Check for old volumes'
      stat:
        path: '{{path.stdout}}/{{pgrole}}'
      register: oldcheck

    - name: 'Migrations'
      block:
        - name: 'Creating new downloads location'
          command: 'mkdir -p {{path.stdout}}/downloads/{{pgrole}}'

      when: oldcheck.stat.exists
      ignore_errors: yes

    - name: 'Ini Check'
      stat:
        path: /opt/appdata/{{pgrole}}/core.conf
      register: inicheck

    # LABELS ######################################################################

    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.enable: 'true'
          traefik.port: '{{intport}}'

          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}},{{tldset}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}:/config'
          - '{{path.stdout}}:{{path.stdout}}'
          - '/mnt/unionfs:/media'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:
          UID: 1000
          GID: 1000

    # MAIN DEPLOYMENT #############################################################
    - name: 'Create scripts directory for {{pgrole}}'
      file:
        path: /opt/appdata/{{pgrole}}/scripts
        state: directory
        owner: 1000
        group: 1000
        mode: 0755

    - name: 'Create plugins directory for {{pgrole}}'
      file:
        path: /opt/appdata/{{pgrole}}/plugins
        state: directory
        owner: 1000
        group: 1000
        mode: 0755

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

    - name: 'Wait 6 Seconds'
      wait_for:
        timeout: 6

    - name: Stop Container
      docker_container:
        name: '{{pgrole}}'
        state: stopped

    # ENDING FOR JELLYFIN ###########################################################

#    - name: 'Waiting for {{pgrole}} to initialize'
#      wait_for:
#        path: '/opt/appdata/{{pgrole}}/core.conf'
#        state: present

    - name: 'Configuring {{pgrole}} for first time use'
      block:
        - name: 'Stopping {{pgrole}}'
          docker_container:
            name: '{{pgrole}}'
            state: stopped

#        - name: Setting plugins directory
#          lineinfile:
#            path: '/opt/appdata/{{pgrole}}/core.conf'
#            regexp: '"plugins_location"'
#            line: '"plugins_location": "/config/plugins",'
#            state: present

        - name: Restart Container
          docker_container:
            name: '{{pgrole}}'
            state: started

      when: not inicheck.stat.exists
